# Matching options
threshold: 0.8
certain_threshold: 0.9
n_neighbors: 3

# Hint matching options
hint_arg_threshold: 0.3
hint_threshold: 0.4
hint_certain_threshold: 0.8
hint_n_neighbors: 7

# Redditbot options
refresh_rate: 60

# User Info
user_info:
  client_id: "XXXXXXXX"
  client_secret: "XXXXXXXX"
  password: "XXXXXXXX"
  user_agent: "XXXXXXXX"
  username: "animalsupportbot"

# Whitelisted Subreddits
whitelisted:
  - testanimalsupportbot
  - vegan
  - debateavegan
  - vegancirclejerk
  - veganforcirclejerkers
  - veganuk

# Blacklisted Subreddits (in addition to defaults)
blacklisted:
  - depression
  - suicidewatch