examples:
- soy farming is ruining the rainforest
- tofu and soymilk is causing deforestation
- the soy that goes into tofu causes just as many problems as beef
- Also isn't it true that tofu that's safe for vegan consumption requires certain ingredients from the amazon jungle that's being deforested?
- Vegetables came maybe is on the amazonic jungle and of course to create it they needed to kill the trees.
- The irony is that stuff like soy has A LOT of pesticides
full_comment: true 
key: soy_farming_is_destroying_the_environment
link: https://www.youtube.com/watch?v=SzOeOfNFpts&list=PL03LZR09P2gQJyBgHk_XE8gbj8j9uFs8G&index=25
title: Soy Farming is Destroying the Environment
enable_resp: true